// pt - nome da propriedade em portugues
// g - se propriedade pod ser exibida no grid
// n - se numérico


// export const ValueFormatters ={
//     n
// };

export default {
    ClassAllBulk: {},
    ClassAll: {},
    ClassCeramic: {},
    Color: {},
    ClassCore: {},
    Envelope: {},
    ClassFoam: {},
    Name: {pt: 'Nome', g: 1, noNum: 1},
    Gid: {},
    HasData: {},
    IsGroup: {},
    ClassMagnetic: {},
    ClassMetal: {},
    Parent: {},
    ClassPolymer: {},
    ClassPolymerElastomer: {},
    ClassPolymerPlastic: {},
    _id: {},
    Rid: {},
    ClassStainlessAlloy: {},
    ClassToolSteel: {},
    ShortName: {},
    ClassWoods: {},
    Price: {pt: 'Preço', g: 1,n:1, unid: ''},
    Density: {pt: 'Densidade', g: 1,n:1, unid: 'kg/m^3'},
    TensileStrength: {pt: 'Resistência à Tração', g: 1,n:1, unid: 'MPa'},
    YoungModulus: {pt: 'Módulo de Young', g: 1,n:1, unid: ''},
    CompressiveStrength: {},
    ThermalConductivity: {},
    FlexuralModulus: {},
    ElectricalResistivity: {},
    MaximumServiceTemperature: {},
    ThermalExpansionCoefficient: {},
    YieldStrength: {},
    SpecificHeatCapacity: {},
    FlexuralStrength: {},
    PoissonRatio: {},
    ShearModulus: {},
    MinimumServiceTemperature: {},
    HardnessVickers: {},
    Elongation: {},
    FractureToughness: {},
    FatigueStrength: {},
    MeltingPoint: {},
    LatentHeatFusion: {},
    GalvanicPotential: {},
    GlassTemperature: {},
    CompressiveModulus: {},
    ShearStrength: {},
    HardnessBrinell: {},
    ImpactStrength23: {},
    MeltTemperature: {},
    PriceDelta: {},
    DensityDelta: {},
    TensileStrengthDelta: {},
    YoungModulusDelta: {},
    CompressiveStrengthDelta: {},
    ThermalConductivityDelta: {},
    FlexuralModulusDelta: {},
    ElectricalResistivityDelta: {},
    MaximumServiceTemperatureDelta: {},
    ThermalExpansionCoefficientDelta: {},
    YieldStrengthDelta: {},
    SpecificHeatCapacityDelta: {},
    FlexuralStrengthDelta: {},
    PoissonRatioDelta: {},
    ShearModulusDelta: {},
    MinimumServiceTemperatureDelta: {},
    HardnessVickersDelta: {},
    ElongationDelta: {},
    FractureToughnessDelta: {},
    FatigueStrengthDelta: {},
    MeltingPointDelta: {},
    LatentHeatFusionDelta: {},
    GalvanicPotentialDelta: {},
    GlassTemperatureDelta: {},
    CompressiveModulusDelta: {},
    ShearStrengthDelta: {},
    HardnessBrinellDelta: {},
    ImpactStrength23Delta: {},
    MeltTemperatureDelta: {},
};